In [1]:
import numpy as np
import pandas as pd

# pivot tables

In [3]:
data = {
    'date': pd.date_range('2023-01-01',periods=20),
    'product': ['A','B','C','D'] * 5,
    'Region': ['east','west','north','south','east','west','north','south','east','west',
               'north','south','east','west','north','south','east','west','north','south'],
    'sales': np.random.randint(100,1000,20),
    'units': np.random.randint(10,100,20),
    'Rep': ['john','mary','bob','alice','john','mary','bob','alice','john','mary',
            'bob','alice','john','mary','bob','alice','john','mary','bob','alice']              
}

df=pd.DataFrame(data)
df['month'] = df['date'].dt.month_name()
df['quarter'] = '0' + df['date'].dt.quarter.astype(str)
df

         date product Region  sales  units    Rep    month quarter
0  2023-01-01       A   east    515     96   john  January      01
1  2023-01-02       B   west    361     31   mary  January      01
2  2023-01-03       C  north    437     23    bob  January      01
3  2023-01-04       D  south    729     79  alice  January      01
4  2023-01-05       A   east    647     11   john  January      01
5  2023-01-06       B   west    936     94   mary  January      01
6  2023-01-07       C  north    820     16    bob  January      01
7  2023-01-08       D  south    803     98  alice  January      01
8  2023-01-09       A   east    106     11   john  January      01
9  2023-01-10       B   west    383     24   mary  January      01
10 2023-01-11       C  north    463     44    bob  January      01
11 2023-01-12       D  south    131     71  alice  January      01
12 2023-01-13       A   east    198     96   john  January      01
13 2023-01-14       B   west    452     20   mary  January      01
14 2023-01-15       C  north    918     58    bob  January      01
15 2023-01-16       D  south    169     73  alice  January      01
16 2023-01-17       A   east    307     53   john  January      01
17 2023-01-18       B   west    641     22   mary  January      01
18 2023-01-19       C  north    821     76    bob  January      01
19 2023-01-20       D  south    327     91  alice  January      01

In [5]:
pd.pivot_table(df,values = 'sales',index = 'Region',columns = 'product',aggfunc='median')

product      A      B      C      D
Region
east     307.0    NaN    NaN    NaN
north      NaN    NaN  820.0    NaN
south      NaN    NaN    NaN  327.0
west       NaN  452.0    NaN    NaN

In [6]:
pivot2 = pd.pivot_table(df,values = ['sales','units'],index = 'Region',columns = 'product') 
pivot2

         sales                      units
product      A      B      C      D     A     B     C     D
Region
east     354.6    NaN    NaN    NaN  53.4   NaN   NaN   NaN
north      NaN    NaN  691.8    NaN   NaN   NaN  43.4   NaN
south      NaN    NaN    NaN  431.8   NaN   NaN   NaN  82.4
west       NaN  554.6    NaN    NaN   NaN  38.2   NaN   NaN

In [8]:
# cross tabs // for counting purpose
pd.crosstab(df['Region'],df['product'])

product  A  B  C  D
Region
east     5  0  0  0
north    0  0  5  0
south    0  0  0  5
west     0  5  0  0