In [1]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv(r'fifa.csv')

In [6]:
df

   player_id        player_name  age
0     P00055         Rodri Fati   26
1     P00070    Ansu Le Normand   19
2     P00066         Gavi Ramos   18
3     P00073      Pedro Cubarsi   20
4     P00059   Alvaro Oyarzabal   23
5     P00072          Dani Gavi   21
6     P00058      Rodri Laporte   27
7     P00078          Ansu Fati   27
8     P00056       Pedro Torres   24
9     P00074    Gavi Le Normand   25
10    P00069     Ferran Cubarsi   24
11    P00071        Marco Mikel   18
12    P00076        Alvaro Gavi   28
13    P00067       Rodri Alonso   25
14    P00057       Gavi Asensio   22
15    P00062     Marco Carvajal   33
16    P00077      Ferran Morata   26
17    P00064      Aymeric Yamal   27
18    P00061          Ansu Alba   28
19    P00068    Alvaro Llorente   19
20    P00060         Ferran Pau   35
21    P00075        Rodri Mikel   25
22    P00063        Dani Garcia   28
23    P00065     Pedro Riquelme   24
24    P00053         Pedro Gavi   36
25    P00054        Gavi Morata   27
26    P01225         Lyle Mvala   38
27    P01241   Sphephelo Mbatha   27
28    P01243       Percy Mkhize   24
29    P01240       Mothobi Xoki   25
30    P00743       Bryan Leiton   27
31    P00748     Oscar Campbell   29
32    P00732       Keylor Calvo   27
33    P00731       Bryan Duarte   28
34    P00730        Joel Borges   25
35    P01198        Omar Hegazi   26
36    P01207          Amr Afsha   25
37    P01215    Mahmoud Ibrahim   24
38    P01206    Mahmoud Soliman   24
39    P01201        Omar Elsaid   26
40    P01217      Mohamed Gomaa   28
41    P01219  Trezeguet Ibrahim   25
42    P01205     Mohamed Hassan   21
43    P01212     Ahmed El-Sayed   23
44    P01204      Mostafa Attia   23
45    P01200     Mohamed Elneny   28
46    P01213      Mostafa Gomaa   29
47    P01211     Trezeguet Said   33
48    P01202   Trezeguet Ashour   25

In [ ]:
# show top 5 row
df.head()

  player_id       player_name  age
0    P00055        Rodri Fati   26
1    P00070   Ansu Le Normand   19
2    P00066        Gavi Ramos   18
3    P00073     Pedro Cubarsi   20
4    P00059  Alvaro Oyarzabal   23

In [9]:
df.loc[1]['age']

np.int64(19)

In [ ]:
# which player has the highest age
df[df['age'] == df['age'].max()]

   player_id player_name  age
26    P01225  Lyle Mvala   38